# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  weight = 20

[[main]]
  name = "Papers"
  parent = "Publications"
  weight = 5
  url = "#pub_journal"

[[main]]
  name = "Chapters"
  parent = "Publications"
  weight = 6
  url = "#pub_chapter"

[[main]]
  name = "Conferences"
  parent = "Publications"
  weight = 7
  url = "#pub_conference"

[[main]]
  name = "Technical Reports"
  parent = "Publications"
  url = "#pub_techrep"
  weight = 10
  
[[main]]
  name = "Teaching and Advisoring"
  weight = 30
  
[[main]]
  name = "Estágios na FGA"
  parent = "Teaching and Advisoring"
  url = "estagios"
  weight = 5